dist: bionic
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
stages:
  - lint
  - test
jobs:
  fast_finish: true
  include:
    - { stage: lint, env: TOXENV=flake8, python: 3.6 }
    - { stage: lint, env: TOXENV=isort, python: 3.6 }
    - stage: deploy
      if: tag IS present
      python: 3.6
      before_deploy: pip install Django>=2.2,<3.0
      deploy:
        skip_existing: true
        provider: pypi
        user: charettes
        distributions: sdist bdist_wheel
        password:
          secure: "K9pNtqnPc7yiCsZp9DpudUmlaKgPNWmns1HvCskNbFhmTxja7omn0xl/a1tbH7sUsbFcDctEZDd2IRer033aYICHGhskShBjPyOCX0TWyJUlrNiovkrcqy8dc36udTJ53FVgxYwCPQ/2AZq7Prw6ya71kw2jPV4Mklqyb6sKxRM="
        on:
          tags: true
install:
- pip install tox coveralls tox-travis
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
